title: Paper Title
tagline: Author, Coauthor
# When building locally, put an empty string. Otherwise, put "/your-repo-name"
# (the "/" is important)
baseurl: "/GAT"
# arXiv ID (as in "https://arxiv.org/abs/[arXiv id]")
arxiv: "https://arxiv.org/abs/1710.10903"
repo:  "https://github.com/PetarV-/GAT"

author:
  name: Contact name
  url: "https://google.com"

# Leave this as is
markdown: kramdown
